### ISSUE TITLE
[REQUEST] allow things to still update on node ui when its closed

### ISSUE THREAD

**Issue by lewislepton** [luboslenco/zui#10]
just spotted this. but when i retract the UI element, it stops the things on screen from updating.
would be great if it still updated.

here is a gif to show

![nodestop](https://cloud.githubusercontent.com/assets/11299322/14583738/f0baa276-0422-11e6-9a83-4c7603cc1af4.gif)

**Comment by luboslenco** [comment]
Can you paste some minimal code? When you retract the UI element the nested stuff is no longer called by the nature of immediate mode ui. But you can probably cache it somehow to suit your needs.

**Comment by lewislepton** [comment]
okay. cool - here is something

```
package;

import kha.Framebuffer;
import kha.graphics2.Graphics;
import kha.Assets;

import zui.Zui;
import zui.Id;

import entity.Line;

class Project {
	public var ui:Zui;
	public var line:Line;
	public function new() {
		ui = new Zui(Assets.fonts.Abel);
		line = new Line();
	}

	public function update():Void {
		line.update();
	}

	public function render(framebuffer:Framebuffer):Void {
		var graphics = framebuffer.g2;
		graphics.begin();
		line.render(graphics);
		gui(graphics);
		graphics.end();
	}
	
	public function gui(graphics:Graphics):Void {
		ui.begin(graphics);
		if (ui.window(Id.window(), 0, 0, 150, 150)){
			if (ui.node(Id.node(), 'node', 0, true)){
				line.x1 = ui.slider(Id.slider(), 'x1', 0, 1000, true, 1);
				line.xSin = ui.slider(Id.slider(), 'sin', 0, 6, true, 100);
				line.y1 = ui.slider(Id.slider(), 'y1', 0, 1000, true, 1);
				line.x2 = ui.slider(Id.slider(), 'x2', 0, 1000, true, 1);
				line.y2 = ui.slider(Id.slider(), 'y2', 0, 1000, true, 1);
			}
		}
		ui.end();
	}
}
```

```
package entity;

import kha.graphics2.Graphics;
import kha.System;

class Line {
	public var x1:Float;
	public var x2:Float;
	public var y1:Float;
	public var y2:Float;
	
	public var x1Sin:Float;
	
	public function new(){
		
	}

	public function update(){
		x1 *= Math.sin(System.time * x1Sin);
	}

	public function render(graphics:Graphics){
		graphics.drawLine(x1, y1, x2, y2, 10);
	}
}
```

**Comment by lewislepton** [comment]
its just mainly so things can carry on for people rather than always having it out flashing itself at you ;)

**Comment by luboslenco** [comment]
Hm I'm confused, there is line.xSin assignment but there is no xSin in Line, maybe it is x1Sin? What happens with the line values when the ui is retracted? Are they preserved? Not sure why the line stops moving since that looks like to be handled in update().

**Comment by lewislepton** [comment]
aye sorry it is x1Sin - just done it on my code now
the line values are preserved in some way. they dont go away when retracted. but once it is, it all stops.

thats what i was thinking about the update as well. bit of a head scratcher

**Comment by luboslenco** [comment]
So what does happen here, is x1 updated?
```
public function update(){
    x1 *= Math.sin(System.time * x1Sin);
}
```

Got one more idea, zui is supposed to be called like this, as it is rendering to a texture on it's own. Not sure if that has an impact. Will have to make this more explicit.
```
graphics.begin();
line.render(graphics);
graphics.end();
gui(graphics);
```

**Comment by lewislepton** [comment]
cool spot. good to know actually - but the problem still happens

aye. `x1` is updated and the UI for `x1Sin` is talking to it to allow the sin to be bigger etc.

**Comment by luboslenco** [comment]
Hm, if the x1 is updated, how could the line not move?
```
graphics.drawLine(x1, y1, x2, y2, 10);
```

Also, you are updating line.x1 in line.update(), but then you overwrite the value with the value a slider returns.

**Comment by lewislepton** [comment]
well one is position, the other is allowing a sine based manipulation. im trying out making some VJ stuff. much like what i done in openframeworks and max/msp - to take kha a little bit away from games ;)

**Comment by lewislepton** [comment]
still needs work though ;)

**Comment by luboslenco** [comment]
You are doing something like this from what I gather:
```
line.x1 *= Math.sin(System.time * x1Sin);
line.x1 = slider();
```

The effect of first line will get erased.

**Comment by luboslenco** [comment]
Or it will be called in reverse, but not sure if it is guaranteed.

**Comment by luboslenco** [comment]
I would just trace the values for
```
graphics.drawLine(x1, y1, x2, y2, 10);
```
If they get updated the line has to move. Otherwise something is acting up.

**Comment by lewislepton** [comment]
cool ok. ill let you know. cheers

**Comment by lewislepton** [comment]
yep. checked. the line is updating perfectly, pretty much in where it should go. then as soon as the node is retracted the number shrinks right down. not going to 0. but staying within `-8 & 8`

i also changed this slightly to this for inside the `Line`, which was what i was looking for
`x1 *= Math.sin(System.time + x1Sin);`

but it still does move just within a certain range

**Comment by luboslenco** [comment]
Maybe there is something weird going on. You could try placing a breakpoint in KodeStudio when ui.node() returns false and inspect if the values are still correct at that point.

**Comment by lewislepton** [comment]
ooooh. found a new thing as well. still within this realm

but as soon as i move my mouse away from the ui on the X axis. the same thing happens. does not happen on the Y though. it seems like it looses focus as soon as you go away from it. but wouldnt know why it would be fine on the Y

![odd happening](https://cloud.githubusercontent.com/assets/11299322/14583981/33418a1c-042b-11e6-8eab-9bebd812c47c.gif)

**Comment by luboslenco** [comment]
With this line
```
x1 *= Math.sin(System.time + x1Sin);
```
You multiply x1 by the value going from -1 to 1, eventually cramming it close to zero. Preserve x1 and use other variable to calculate that.

**Comment by luboslenco** [comment]
Closing down, feel free to reopen if the problem persist.
