### ISSUE TITLE
[REQUEST] to allow translating of UI

### ISSUE THREAD

**Issue by lewislepton** [luboslenco/zui#11]
this is something ive just come thorugh as well.

gui is outside the render path of the render in the Project.hx - but when doing a translate with my line/entity. it moves the UI, but also does not move the editable elements. so it shows the UI in the other corner, but the elements in which i click stay in the top left

here is a gif to show

same code as the previous https://github.com/luboslenco/zui/issues/10

![translate](https://cloud.githubusercontent.com/assets/11299322/14583855/e074c33e-0426-11e6-8253-61f7d8186e8b.gif)

**Comment by lewislepton** [comment]
tohugh i say the same code. it only has this addition

```
public function render(framebuffer:Framebuffer):Void {
		var graphics = framebuffer.g2;
		graphics.begin();
		line.render(graphics);
		graphics.transformation = FastMatrix3.translation(512, 384);
		graphics.end();
		gui(graphics);
	}
```

**Comment by luboslenco** [comment]
Not sure how to go around this, as transformation translates the rendering but the input is not translated. You can probably set Zui,autoNotifyMouseEvents to false and call onMouse() events manually with translated mouse coords.

**Comment by lewislepton** [comment]
okay. cool. for now ill keep it simple for now. but will make a note ;)

**Comment by luboslenco** [comment]
Please use ui.window() coordinates to translate UI for now, or use the method mentioned in my previous comment and process input manually.
