### ISSUE TITLE
[POSSIBLE BUG] static objects still move, even if not within update

### ISSUE THREAD

**Issue by lewislepton** [luboslenco/zui#14]
i know i have talked about this regarding moving objects that were located in update. but on objects, which are static, they are affected by the node window and the cursor moving away from it.

its really weird. i know its an odd setting with my button used to move the block. but strange that it moves without anything. i know it is about stopping it another way. but something not even updating is being fired off.
here is a gif to show. also shows the code and cursor not even touching the button, but the block still moves, once it is away from the node window

![glitchzui](https://cloud.githubusercontent.com/assets/11299322/15978854/9f111688-2f58-11e6-9988-40631387fc02.gif)

**Comment by luboslenco** [comment]
As soon as you move the mouse out of window, zui will no longer run to preserve resources. Your rectangle jumps as soon as leave the zui window or stop interacting with it, so my guess is that your values are not stored correctly. The easiest way is to inspect what is going on in the KodeStudio debugger.
