### ISSUE TITLE
[REQUEST] allow starting value inside objects

### ISSUE THREAD

**Issue by lewislepton** [luboslenco/zui#15]
just as a additional thing. it would be cool if you could have a slider/toggle/radio etc, start at a certain value. so just before setting say the minimum value or after the max value, have a `startAt` variable. so when you set it at say `200`, it opens all the time at `200`, also sending that value out right away

**Comment by luboslenco** [comment]
There seems to be 'initValue' parameter for slider() and similar for others, or is this a different thing?

**Comment by lewislepton** [comment]
aaahhh my mistake. overlooked that. cheers ;)
