### ISSUE TITLE
[REQUEST] stop items to be clicked behind ui

### ISSUE THREAD

**Issue by lewislepton** [luboslenco/zui#16]
it would be great to allow any mouse interactions that happen below the ui to stop

so say if i am drawing or positioning something with the mouse click, it would be good if that mouse click was not registered when using the mouse with the ui. so it only allows the change in the ui, but does not register the click underneath to what you are editing

if that makes sense?

**Comment by sh-dave** [comment]
Doesn't make much sense to have Zui interfere with Kha's events imo.

You can set Zui.autoNotifyMouseEvents=false before creating the Zui instance, and forward the events manually with Zui.onMouseXXX(...) if you want that behavior.

**Comment by lewislepton** [comment]
aye. glad im not alone. looking for something to stop it as you said, but not seen anything...

**Comment by luboslenco** [comment]
Suggestion by Dave should be able to accomplish this. Please reopen if anything goes wrong.

**Comment by sh-dave** [comment]
I think you misunderstood @lewislepton. It's good the way it is implemented. Zui just connects to kha.input.Mouse.get().notify(...) as you do in your code. And it doesn't make sense to have Zui suppress the kha mouse messages. What you can do to accomplish this:

```haxe
class MyApp {
	var z : zui.Zui;
	
	var windowX = 0;
	var windowY = 0;
	var windowWidth = 256;
	var windowHeight = 256;
	
	public function new() {
		zui.Zui.autoNotifyMouseEvents = false; // zui won't handle mouse input on it's own now
		z = new zui.Zui(...);
		
		kha.input.Mouse.get().notify(mouse_downHandler, ...);
	}
		
	function mouse_downHandler( button : Int, mx : Int, my : Int ) {
		// if zui's window area was hit,  we forward the event to it, but don't handle our stuff
		if (mx >= windowX && mx <= windowWidth && my >= windowY && my <= windowHeight) {
			z.onMouseDown(button, mx, my);
		} else {
			doMyStuff();
		}
	}
	
	function render( fb : kha.Framebuffer ) {
		...
			z.begin(fb.g2);
				if (z.window(zui.Id.window(), windowX, windowY, windowWidth, windowHeight)) {
					...
				}
			z.end();
		...
	}	
}
```
