### ISSUE TITLE
ZUI Usage for Other than Debugging

### ISSUE THREAD

**Issue by primesoftware** [luboslenco/zui#17]
Is there a reason you say ZUI is mainly useful for debugging? Performance reasons? I am planning on making a desktop application that will require windows being drawn. I don't see any reason ZUI wouldn't work for that purpose. I'd say give yourself more credit unless I'm missing something!

**Comment by luboslenco** [comment]
Performance should be good, if there are issues that can be fixed. My main concerns on building real applications are:
- No fancy layouts
- No skinning, only hard-coded colors
- No advanced elements

I still love the brutally minimal approach of immediate ui and with some effort all of these can be improved upon, but will likely take some time. :)
