### ISSUE TITLE
allow slider values to be updated via code

### ISSUE THREAD

**Issue by sangohan** [luboslenco/zui#20]
sliders are very useful, but it only allows getting of values. It does not allow values to be set from some other process (such as a randomiser). 

a quick fix would be to expose the `sliderState` field, and that will allow programs to set the value directly, and the UI would update correctly as well. The other *state fields could also be exposed in a similar fashion to allow for finer grain control of the UI states.

**Comment by luboslenco** [comment]
Merged!

**Comment by sangohan** [comment]
Yay! 
Love the library btw!

**Comment by luboslenco** [comment]
Happy to hear! Improvements & a little cleanup still needed, but hopefully soon.

**Comment by sangohan** [comment]
@Disar : the maps are removed. If you have access to the handle for the UI widget, you can set the public 'value' field. Try that and see how that works?
