### ISSUE TITLE
[QUESTION] using zui outside of framebuffer & backbuffer

### ISSUE THREAD

**Issue by lewislepton** [luboslenco/zui#30]
this is something that i have recently tried to fix.
but im using backbuffer/framebuffer or scaling things. but dont want the ui to be affected. tried a few other methods. but the ui still seems to be moving/scaling.

how can the ui be seperate completely so does not scale at all, but stays in the top left corner [or wherever you choose to place it?

**Comment by sh-dave** [comment]
Just create a rendertarget for Zui to render into and draw that however you like.
